package config

import "fmt"

type Generator struct {
	Vendor   string
	LocalAS  int
	RouterID string
}

func NewGenerator(vendor string, localAS int) *Generator {
	return &Generator{
		Vendor:  vendor,
		LocalAS: localAS,
	}
}

func (g *Generator) GenerateBGPConfig(neighbors []NeighborConfig) string {
	switch g.Vendor {
	case "cisco":
		return g.generateCiscoConfig(neighbors)
	case "juniper":
		return g.generateJuniperConfig(neighbors)
	case "mikrotik":
		return g.generateMikrotikConfig(neighbors)
	default:
		return g.generateCiscoConfig(neighbors)
	}
}

type NeighborConfig struct {
	NeighborIP    string
	RemoteAS      int
	Description   string
	PrefixListIn  string
	PrefixListOut string
	RouteMapIn    string
	RouteMapOut   string
}

func (g *Generator) generateCiscoConfig(neighbors []NeighborConfig) string {
	config := fmt.Sprintf(`!
! Cisco IOS BGP Configuration
! Generated by bgpin
!
router bgp %d
 bgp log-neighbor-changes
 no synchronization
`, g.LocalAS)

	for _, neighbor := range neighbors {
		config += fmt.Sprintf(" neighbor %s remote-as %d\n", neighbor.NeighborIP, neighbor.RemoteAS)
		if neighbor.Description != "" {
			config += fmt.Sprintf(" neighbor %s description %s\n", neighbor.NeighborIP, neighbor.Description)
		}
		config += fmt.Sprintf(" neighbor %s next-hop-self\n", neighbor.NeighborIP)
		config += fmt.Sprintf(" neighbor %s soft-reconfiguration inbound\n", neighbor.NeighborIP)
		if neighbor.PrefixListIn != "" {
			config += fmt.Sprintf(" neighbor %s prefix-list %s in\n", neighbor.NeighborIP, neighbor.PrefixListIn)
		}
		if neighbor.PrefixListOut != "" {
			config += fmt.Sprintf(" neighbor %s prefix-list %s out\n", neighbor.NeighborIP, neighbor.PrefixListOut)
		}
		if neighbor.RouteMapIn != "" {
			config += fmt.Sprintf(" neighbor %s route-map %s in\n", neighbor.NeighborIP, neighbor.RouteMapIn)
		}
		if neighbor.RouteMapOut != "" {
			config += fmt.Sprintf(" neighbor %s route-map %s out\n", neighbor.NeighborIP, neighbor.RouteMapOut)
		}
	}

	config += `!
 ip bgp-community new-format
!
end
`
	return config
}

func (g *Generator) generateJuniperConfig(neighbors []NeighborConfig) string {
	config := fmt.Sprintf(`# Juniper JunOS BGP Configuration
# Generated by bgpin

protocols {
    bgp {
        group bgp-peers {
            type external;
            local-address 0.0.0.0;
            export export-policy;
            import import-policy;
`)

	for _, neighbor := range neighbors {
		config += fmt.Sprintf(`            neighbor %s {
                peer-as %d;
`, neighbor.NeighborIP, neighbor.RemoteAS)
		if neighbor.Description != "" {
			config += fmt.Sprintf(`                description "%s";
`, neighbor.Description)
		}
		config += `            }
`
	}

	config += `        }
    }
}

policy-options {
    policy-statement export-policy {
        term 1 {
            from protocol direct;
            then accept;
        }
        term default {
            then reject;
        }
    }
    policy-statement import-policy {
        term 1 {
            then accept;
        }
    }
}
`
	return config
}

func (g *Generator) generateMikrotikConfig(neighbors []NeighborConfig) string {
	config := fmt.Sprintf(`# MikroTik RouterOS BGP Configuration
# Generated by bgpin

/routing bgp instance
set default as=%d
`, g.LocalAS)

	for i, neighbor := range neighbors {
		config += fmt.Sprintf(`
/routing bgp peer
add name=peer%d instance=default remote-address=%s remote-as=%d`, i+1, neighbor.NeighborIP, neighbor.RemoteAS)
		if neighbor.Description != "" {
			config += fmt.Sprintf(` comment="%s"`, neighbor.Description)
		}
		config += "\n"
	}

	return config
}

func (g *Generator) GeneratePrefixList(prefixes []string, name string, action string) string {
	switch g.Vendor {
	case "cisco":
		return g.generateCiscoPrefixList(prefixes, name, action)
	case "juniper":
		return g.generateJuniperPrefixList(prefixes, name, action)
	case "mikrotik":
		return g.generateMikrotikPrefixList(prefixes, name, action)
	default:
		return g.generateCiscoPrefixList(prefixes, name, action)
	}
}

func (g *Generator) generateCiscoPrefixList(prefixes []string, name string, action string) string {
	config := fmt.Sprintf("!\n! Prefix List Configuration\n!\nip prefix-list %s seq 10 permit %s\n", name, action)

	for i, prefix := range prefixes {
		config += fmt.Sprintf("ip prefix-list %s seq %d permit %s\n", name, (i+1)*10, prefix)
	}

	return config + "!\n"
}

func (g *Generator) generateJuniperPrefixList(prefixes []string, name string, action string) string {
	config := fmt.Sprintf("policy-options {\n    prefix-list %s {\n", name)

	for _, prefix := range prefixes {
		config += fmt.Sprintf("        %s %s;\n", action, prefix)
	}

	config += "    }\n}\n"
	return config
}

func (g *Generator) generateMikrotikPrefixList(prefixes []string, name string, action string) string {
	config := "/ip firewall address-list\n"

	for _, prefix := range prefixes {
		config += fmt.Sprintf("add list=%s address=%s\n", name, prefix)
	}

	return config
}

func (g *Generator) GenerateRouteMap(name string, action string) string {
	switch g.Vendor {
	case "cisco":
		return g.generateCiscoRouteMap(name, action)
	case "juniper":
		return g.generateJuniperRouteMap(name, action)
	case "mikrotik":
		return g.generateMikrotikRouteMap(name, action)
	default:
		return g.generateCiscoRouteMap(name, action)
	}
}

func (g *Generator) generateCiscoRouteMap(name string, action string) string {
	return fmt.Sprintf(`!
route-map %s permit 10
 match ip address prefix-list ALLOW_ALL
 set local-preference 100
!
route-map %s permit 20
 set community %s
!
`, name, name, action)
}

func (g *Generator) generateJuniperRouteMap(name string, action string) string {
	return fmt.Sprintf(`policy-options {
    policy-statement %s {
        term 1 {
            from {
                protocol bgp;
            }
            then {
                community add %s;
                accept;
            }
        }
        term default {
            then reject;
        }
    }
}
`, name, action)
}

func (g *Generator) generateMikrotikRouteMap(name string, action string) string {
	return fmt.Sprintf(`/routing filter
add chain=%s action=%s bgp-as-path-length=0-25
`, name, action)
}
